# coding: utf-8

SUBJECT_AREAS = [
    'Health Sciences',
    'Agricultural Sciences',
    'Human Sciences',
    'Biological Sciences',
    'Exact and Earth Sciences',
    'Engineering',
    'Applied Social Sciences',
    'Linguistics, Letters and Arts'
]

ISO_639_1 = {
    u"BE": u"Belarusian",
    u"BG": u"Bulgarian",
    u"VE": u"Venda",
    u"BA": u"Bashkir",
    u"WA": u"Walloon",
    u"WO": u"Wolof",
    u"BM": u"Bambara",
    u"BN": u"Bengali",
    u"BO": u"Tibetan",
    u"BH": u"Bihari languages",
    u"BI": u"Bislama",
    u"MH": u"Marshallese",
    u"BR": u"Breton",
    u"BS": u"Bosnian",
    u"JA": u"Japanese",
    u"RU": u"Russian",
    u"RW": u"Kinyarwanda",
    u"TL": u"Tagalog",
    u"RM": u"Romansh",
    u"RN": u"Rundi",
    u"RO": u"Romanian",
    u"JV": u"Javanese",
    u"GV": u"Manx",
    u"GU": u"Gujarati",
    u"GD": u"Gaelic",
    u"GA": u"Irish",
    u"SV": u"Swedish",
    u"GN": u"Guarani",
    u"GL": u"Galician",
    u"OM": u"Oromo",
    u"TN": u"Tswana",
    u"OJ": u"Ojibwa",
    u"FA": u"Persian",
    u"OC": u"Occitan (post 1500)",
    u"SS": u"Swati",
    u"SU": u"Sundanese",
    u"SR": u"Serbian",
    u"OS": u"Ossetian",
    u"OR": u"Oriya",
    u"HZ": u"Herero",
    u"HY": u"Armenian",
    u"HR": u"Croatian",
    u"SW": u"Swahili",
    u"HT": u"Haitian",
    u"HU": u"Hungarian",
    u"HI": u"Hindi",
    u"HO": u"Hiri Motu",
    u"HA": u"Hausa",
    u"HE": u"Hebrew",
    u"PS": u"Pushto",
    u"PT": u"Portuguese",
    u"SK": u"Slovak",
    u"PA": u"Panjabi",
    u"SO": u"Somali",
    u"PI": u"Pali",
    u"AK": u"Akan",
    u"PL": u"Polish",
    u"SN": u"Shona",
    u"EL": u"Greek",
    u"EO": u"Esperanto",
    u"EN": u"English",
    u"ZH": u"Chinese",
    u"SM": u"Samoan",
    u"EE": u"Ewe",
    u"AM": u"Amharic",
    u"ZA": u"Zhuang",
    u"EU": u"Basque",
    u"ET": u"Estonian",
    u"VO": u"Volapük",
    u"SA": u"Sanskrit",
    u"ES": u"Spanish",
    u"MG": u"Malagasy",
    u"UZ": u"Uzbek",
    u"ML": u"Malayalam",
    u"MN": u"Mongolian",
    u"MI": u"Maori",
    u"AS": u"Assamese",
    u"MK": u"Macedonian",
    u"UR": u"Urdu",
    u"MT": u"Maltese",
    u"MS": u"Malay",
    u"MR": u"Marathi",
    u"UG": u"Uighur; Uyghur",
    u"MY": u"Burmese",
    u"FR": u"French",
    u"FY": u"Western Frisian",
    u"AY": u"Aymara",
    u"FF": u"Fulah",
    u"ZU": u"Zulu",
    u"FI": u"Finnish",
    u"FJ": u"Fijian",
    u"FO": u"Faroese",
    u"NL": u"Dutch; Flemish",
    u"NN": u"Norwegian Nynorsk",
    u"NO": u"Norwegian",
    u"NA": u"Nauru",
    u"NB": u"Bokmål, Norwegian",
    u"ND": u"Ndebele, North",
    u"NE": u"Nepali",
    u"NG": u"Ndonga",
    u"NY": u"Chichewa",
    u"NR": u"Ndebele, South",
    u"NV": u"Navajo",
    u"XH": u"Xhosa",
    u"CH": u"Chamorro",
    u"CO": u"Corsican",
    u"CA": u"Catalan; Valencian",
    u"CE": u"Chechen",
    u"CY": u"Welsh",
    u"CS": u"Czech",
    u"CR": u"Cree",
    u"CV": u"Chuvash",
    u"CU": u"Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
    u"KA": u"Georgian",
    u"KG": u"Kongo",
    u"KK": u"Kazakh",
    u"KJ": u"Kuanyama; Kwanyama",
    u"KI": u"Kikuyu; Gikuyu",
    u"KO": u"Korean",
    u"KN": u"Kannada",
    u"KM": u"Central Khmer",
    u"KL": u"Kalaallisut",
    u"KS": u"Kashmiri",
    u"KR": u"Kanuri",
    u"SI": u"Sinhala",
    u"KW": u"Cornish",
    u"KV": u"Komi",
    u"KU": u"Kurdish",
    u"SL": u"Slovenian",
    u"SC": u"Sardinian",
    u"KY": u"Kirghiz",
    u"SG": u"Sango",
    u"SE": u"Northern Sami",
    u"SD": u"Sindhi",
    u"YI": u"Yiddish",
    u"YO": u"Yoruba",
    u"DE": u"German",
    u"DA": u"Danish",
    u"DZ": u"Dzongkha",
    u"DV": u"Divehi",
    u"LG": u"Ganda",
    u"LB": u"Luxembourgish",
    u"LA": u"Latin",
    u"LN": u"Lingala",
    u"LO": u"Lao",
    u"TT": u"Tatar",
    u"TR": u"Turkish",
    u"TS": u"Tsonga",
    u"LI": u"Limburgan",
    u"LV": u"Latvian",
    u"TO": u"Tonga",
    u"LT": u"Lithuanian",
    u"LU": u"Luba-Katanga",
    u"TK": u"Turkmen",
    u"TH": u"Thai",
    u"TI": u"Tigrinya",
    u"TG": u"Tajik",
    u"TE": u"Telugu",
    u"TA": u"Tamil",
    u"AA": u"Afar",
    u"AB": u"Abkhazian",
    u"AE": u"Avestan",
    u"UK": u"Ukrainian",
    u"AF": u"Afrikaans",
    u"VI": u"Vietnamese",
    u"IS": u"Icelandic",
    u"IU": u"Inuktitut",
    u"IT": u"Italian",
    u"AN": u"Aragonese",
    u"II": u"Sichuan Yi",
    u"IK": u"Inupiaq",
    u"AR": u"Arabic",
    u"IO": u"Ido",
    u"AV": u"Avaric",
    u"IA": u"Interlingua",
    u"AZ": u"Azerbaijani",
    u"IE": u"Interlingue",
    u"ID": u"Indonesian",
    u"IG": u"Igbo",
    u"QU": u"Quechua",
    u"TY": u"Tahitian",
    u"ST": u"Sotho, Southern",
    u"TW": u"Twi",
    u"SQ": u"Albanian"
}

ISO_3166 = {
    'BD': u'Bangladesh',
    'BE': u'Belgium',
    'BF': u'Burkina Faso',
    'BG': u'Bulgaria',
    'BA': u'Bosnia and Herzegovina',
    'BB': u'Barbados',
    'WF': u'Wallis and Futuna',
    'BL': u'Saint Barthélemy',
    'BM': u'Bermuda',
    'BN': u'Brunei Darussalam',
    'BO': u'Bolivia',
    'BH': u'Bahrain',
    'BI': u'Burundi',
    'BJ': u'Benin',
    'BT': u'Bhutan',
    'BU': u'Burma',
    'BV': u'Bouvet Island',
    'BW': u'Botswana',
    'WS': u'Samoa',
    'BQ': u'British Antarctic Territory',
    'BR': u'Brazil',
    'BS': u'Bahamas',
    'JE': u'Jersey',
    'WK': u'Wake Island',
    'BY': u'Byelorussian SSR',
    'BZ': u'Belize',
    'RU': u'Russian Federation',
    'RW': u'Rwanda',
    'PC': u'Pacific Islands',
    'TL': u'Timor-Leste',
    'JT': u'Johnston Island',
    'TM': u'Turkmenistan',
    'TJ': u'Tajikistan',
    'RO': u'Romania',
    'RH': u'Southern Rhodesia',
    'TK': u'Tokelau',
    'GW': u'Guinea-Bissau',
    'GU': u'Guam',
    'GT': u'Guatemala',
    'GS': u'South Georgia and the South Sandwich Islands',
    'GR': u'Greece',
    'GQ': u'Equatorial Guinea',
    'GP': u'Guadeloupe',
    'JP': u'Japan',
    'GY': u'Guyana',
    'GG': u'Guernsey',
    'GF': u'French Guiana',
    'GE': u'Gilbert and Ellice Islands',
    'GD': u'Grenada',
    'GB': u'United Kingdom',
    'GA': u'Gabon',
    'SV': u'El Salvador',
    'GN': u'Guinea',
    'GM': u'Gambia',
    'GL': u'Greenland',
    'GI': u'Gibraltar',
    'GH': u'Ghana',
    'OM': u'Oman',
    'TN': u'Tunisia',
    'JM': u'Jamaica',
    'JO': u'Jordan',
    'HR': u'Croatia',
    'HV': u'Upper Volta',
    'HT': u'Haiti',
    'HU': u'Hungary',
    'HK': u'Hong Kong',
    'HN': u'Honduras',
    'HM': u'Heard Island and McDonald Islands',
    'VD': u'Viet-Nam',
    'VE': u'Venezuela',
    'PR': u'Puerto Rico',
    'PS': u'Palestine',
    'UA': u'Ukraine',
    'PW': u'Palau',
    'PT': u'Portugal',
    'PU': u'United States Miscellaneous Pacific Islands',
    'PZ': u'Panama Canal Zone',
    'PY': u'Paraguay',
    'IQ': u'Iraq',
    'PA': u'Panama',
    'PF': u'French Polynesia',
    'PG': u'Papua New Guinea',
    'PE': u'Peru',
    'PK': u'Pakistan',
    'PH': u'Philippines',
    'PN': u'Pitcairn',
    'PL': u'Poland',
    'PM': u'Saint Pierre and Miquelon',
    'ZM': u'Zambia',
    'EH': u'Western Sahara',
    'EE': u'Estonia',
    'EG': u'Egypt',
    'ZA': u'South Africa',
    'EC': u'Ecuador',
    'IT': u'Italy',
    'VN': u'Viet Nam',
    'SB': u'Solomon Islands',
    'ET': u'Ethiopia',
    'SO': u'Somalia',
    'ZW': u'Zimbabwe',
    'SA': u'Saudi Arabia',
    'ES': u'Spain',
    'ER': u'Eritrea',
    'ME': u'Montenegro',
    'MD': u'Moldova',
    'MG': u'Madagascar',
    'MF': u'Saint Martin',
    'MA': u'Morocco',
    'MC': u'Monaco',
    'UZ': u'Uzbekistan',
    'MM': u'Myanmar',
    'ML': u'Mali',
    'MO': u'Macao',
    'MN': u'Mongolia',
    'MI': u'Midway Islands',
    'MH': u'Marshall Islands',
    'MK': u'Macedonia',
    'MU': u'Mauritius',
    'MT': u'Malta',
    'MW': u'Malawi',
    'MV': u'Maldives',
    'MQ': u'Martinique',
    'MP': u'Northern Mariana Islands',
    'MS': u'Montserrat',
    'MR': u'Mauritania',
    'IM': u'Isle of Man',
    'UG': u'Uganda',
    'TZ': u'Tanzania',
    'MY': u'Malaysia',
    'MX': u'Mexico',
    'IL': u'Israel',
    'FQ': u'French Southern and Antarctic Territories',
    'FR': u'France',
    'IO': u'British Indian Ocean Territory',
    'SH': u'Saint Helena',
    'RE': u'Réunion',
    'SJ': u'Svalbard and Jan Mayen',
    'FI': u'Finland',
    'FJ': u'Fiji',
    'FK': u'Falkland Islands',
    'FM': u'Micronesia',
    'FO': u'Faroe Islands',
    'NH': u'New Hebrides',
    'NI': u'Nicaragua',
    'NL': u'Netherlands',
    'NO': u'Norway',
    'NA': u'Namibia',
    'VU': u'Vanuatu',
    'NC': u'New Caledonia',
    'NE': u'Niger',
    'NF': u'Norfolk Island',
    'NG': u'Nigeria',
    'NZ': u'New Zealand',
    'ZR': u'Zaire',
    'NP': u'Nepal',
    'NQ': u'Dronning Maud Land',
    'NR': u'Nauru',
    'NT': u'Neutral Zone',
    'NU': u'Niue',
    'CK': u'Cook Islands',
    'CI': u"Côte d'Ivoire",
    'CH': u'Switzerland',
    'CO': u'Colombia',
    'CN': u'China',
    'CM': u'Cameroon',
    'CL': u'Chile',
    'CC': u'Cocos',
    'CA': u'Canada',
    'CG': u'Congo',
    'CF': u'Central African Republic',
    'CD': u'Congo',
    'CZ': u'Czech Republic',
    'CY': u'Cyprus',
    'CX': u'Christmas Island',
    'CS': u'Czechoslovakia',
    'CR': u'Costa Rica',
    'CW': u'Curaçao',
    'CV': u'Cabo Verde',
    'CU': u'Cuba',
    'CT': u'Canton and Enderbury Islands',
    'SZ': u'Swaziland',
    'SY': u'Syrian Arab Republic',
    'SX': u'Sint Maarten',
    'KG': u'Kyrgyzstan',
    'KE': u'Kenya',
    'SS': u'South Sudan',
    'SR': u'Suriname',
    'KI': u'Kiribati',
    'KH': u'Cambodia',
    'KN': u'Saint Kitts and Nevis',
    'KM': u'Comoros',
    'ST': u'Sao Tome and Principe',
    'SK': u'Slovakia',
    'KR': u'Korea',
    'SI': u'Slovenia',
    'KP': u'Korea',
    'KW': u'Kuwait',
    'SN': u'Senegal',
    'SM': u'San Marino',
    'SL': u'Sierra Leone',
    'SC': u'Seychelles',
    'KZ': u'Kazakhstan',
    'KY': u'Cayman Islands',
    'SG': u'Singapore',
    'SE': u'Sweden',
    'SD': u'Sudan',
    'DO': u'Dominican Republic',
    'DM': u'Dominica',
    'DJ': u'Djibouti',
    'DK': u'Denmark',
    'VG': u'Virgin Islands',
    'DD': u'German Democratic Republic',
    'DE': u'Germany',
    'YE': u'Yemen',
    'YD': u'Yemen',
    'DZ': u'Algeria',
    'US': u'United States',
    'DY': u'Dahomey',
    'UY': u'Uruguay',
    'YU': u'Yugoslavia',
    'YT': u'Mayotte',
    'UM': u'United States Minor Outlying Islands',
    'LB': u'Lebanon',
    'LC': u'Saint Lucia',
    'LA': u"Lao People's Democratic Republic",
    'TV': u'Tuvalu',
    'TW': u'Taiwan',
    'TT': u'Trinidad and Tobago',
    'TR': u'Turkey',
    'LK': u'Sri Lanka',
    'TP': u'East Timor',
    'LI': u'Liechtenstein',
    'LV': u'Latvia',
    'TO': u'Tonga',
    'LT': u'Lithuania',
    'LU': u'Luxembourg',
    'LR': u'Liberia',
    'LS': u'Lesotho',
    'TH': u'Thailand',
    'TF': u'French Southern Territories',
    'TG': u'Togo',
    'TD': u'Chad',
    'TC': u'Turks and Caicos Islands',
    'LY': u'Libya',
    'VA': u'Holy See',
    'VC': u'Saint Vincent and the Grenadines',
    'AE': u'United Arab Emirates',
    'AD': u'Andorra',
    'AG': u'Antigua and Barbuda',
    'AF': u'Afghanistan',
    'AI': u'Anguilla',
    'VI': u'Virgin Islands',
    'IS': u'Iceland',
    'IR': u'Iran',
    'AM': u'Armenia',
    'AL': u'Albania',
    'AO': u'Angola',
    'AN': u'Netherlands Antilles',
    'AQ': u'Antarctica',
    'AS': u'American Samoa',
    'AR': u'Argentina',
    'AU': u'Australia',
    'AT': u'Austria',
    'AW': u'Aruba',
    'IN': u'India',
    'AX': u'Âland Islands',
    'AZ': u'Azerbaijan',
    'IE': u'Ireland',
    'ID': u'Indonesia',
    'RS': u'Serbia',
    'QA': u'Qatar',
    'MZ': u'Mozambique'
}
