language: python
python:
  - "3.13"
env:
  - ANALYTICS_SETTINGS_FILE=./config.ini
install: 
  - pip install --upgrade deps/scielojcr-1.3.0-py2.py3-none-any.whl
  - python setup.py install
script:
  - python -m unittest discover -s tests
before_script:
  - cp ./development.ini-TEMPLATE ./config.ini
