FROM python:3.13-slim
ENV PYTHONUNBUFFERED 1

RUN apt-get update
RUN apt-get install --yes build-essential git libmemcached-dev zlib1g-dev


COPY . /app
COPY development.ini-TEMPLATE /app/config.ini

WORKDIR /app

RUN pip install --upgrade pip "setuptools<81" wheel && \
    pip install gunicorn && \
    pip install --upgrade deps/scielojcr-1.3.0-py2.py3-none-any.whl && \
    pip install -r requirements.txt && \
    pip install .
RUN chown -R nobody:nogroup /app

ENV ANALYTICS_SETTINGS_FILE=/app/config.ini

USER nobody

CMD ["gunicorn", "--paste", "/app/config.ini", "-b", "0.0.0.0", "--forwarded-allow-ips", "*", "--log-config", "/app/config.ini", "--timeout", "600"]
